### PR TITLE
MR1 Sumcoin following Noxon instruction link

### PR DESCRIPTION
**Pull request by 5053s**
### following Noxon instruction link  ###

# Pull request template

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] branch rebased on `master`
- [ ] styleguide check `npm run validate`
- [ ] good naming
- [x] keep simple
- [ ] video or screenshot attached
- [ ] testing instruction attached
- [ ] check your PR once again

### What and how to test

To test it locally run ```git fetch && fit checkout twelveWordsCreateBug``` where twelveWordsCreateBug is a name of this branch (see under title) OR ```git fetch origin refs/pull/2590/merge:pr2590 && git checkout pr2590``` where 2590 is number of this pull request

```npm i && npm run build:mainnet``` then run MultiCurrencyWallet/build.mainnet/index.html in browse

### CODE REVIEW

**Comment by noxonsu** [comment]
- [ ] pass checklist and CI please, https://screenshots.wpmix.net/chrome_WTAC0x5YUKHeRYLltKN5bYcmouy2CHEV.png 
- [ ] remove SMS 2fa (need additional changes on our 2fa server, not need at this time)

**Comment by shendel** [comment]
Next step
image
Your need create sum.js actions file (look at actions/btc.js)
Your need make implementations of some methods (requered)

login,
send,
getBalance,
getTransaction,
fetchBalance
fetchTxInfo
getTx
getAllMyAdresses
getDataByAdress
getTxRouter
getInvoices (if your want use invoices with your cryptocoin)

**Comment by 5053s** [comment]
resuming work on checklist soon

**Comment by noxonsu** [comment]
another reference https://github.com/swaponline/MultiCurrencyWallet/pull/2891 , check it out (they also add todolist for blockchain connection here https://github.com/swaponline/MultiCurrencyWallet/pull/2891/files#diff-6cc902cb3384160506e4b4780beea036 )

**Comment by iower** [comment]
Seems outdated

**Pull request closed without merging**
