### PR TITLE
WIP: metamask - changes - dApp support (Trust, Metamask...)

### PR DESCRIPTION
**Pull request by shendel**
live: https://pr3552.swaponline.site/ 

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] Good naming, keep simple
- [x] Tested desktop/mobile
- [x] Tested bright/dark
- [x] Tested en/ru
- [x] Affects money; I checked the functionality once again
- [x] I checked the PR once again

### Original issue

#

### CODE REVIEW

**Comment by shendel** [comment]
https://github.com/swaponline/MultiCurrencyWallet/issues/3543

**Review by noxonsu — APPROVED** [review]

**Comment by noxonsu** [comment]
- [ ] не показывает окно "переключите сеть" (поменял в метамаске на кован, мейннет и ринкеби, везде переподключился норм и баланс подхватил)

**Comment by noxonsu** [comment]
- [ ] check liuality interoperability https://github.com/liquality/wallet/commit/afb68bc70a995253c8ae38611c9bdc1431f9d59e ,  @monokh can you review it ?

**Comment by noxonsu** [comment]
- [ ] нажал deposit и выбрал эфир перескочило на https://swaponline.github.io/#/eth/Not%20connected/receive  и там ероры

**Comment by monokh** [comment]
It seemed to work from what I tried. We conform to the ethereum API so as long as it works with metamask, users shouldn't have an issue with liquality wallet.
Also consider that the Liquality wallet also provides bitcoin injection (`window.bitcoin`)
It has the core functions to function for any bitcoin application: `getAddresses`, `signMessage`, `sendTransaction`, `signPSBT` ...
The [swap UI here](https://liquality.io/swap-testnet-dev) can swap using the liquality wallet on both sides of the atomic swap
[This example](https://codesandbox.io/s/liquality-psbt-signer-9k5vb?file=/src/index.js) also demonstrates the core functionality.

**Comment by monokh** [comment]
Just realised `signPSBT` is not available in prod yet, so some parts of the examples will not work until the next release

**Pull request merged**
