### PR TITLE
Add ghost support

### PR DESCRIPTION
**Pull request by JoaoCampos89**
# Add Ghost Support

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [ ] branch rebased on `master`
- [ ] styleguide check `npm run validate`
- [ ] good naming
- [ ] keep simple
- [ ] video or screenshot attached
- [ ] testing instruction attached
- [ ] check your PR once again

### What and how to test

To test it locally run ```git fetch && fit checkout twelveWordsCreateBug``` where twelveWordsCreateBug is a name of this branch (see under title) OR ```PRID=2812; git fetch origin refs/pull/$PRID/merge:pr$PRID && git checkout pr$PRID``` where PRID is number of this pull request

```npm i && npm run build:mainnet``` then run MultiCurrencyWallet/build.mainnet/index.html in browse

### CODE REVIEW

**Comment by shendel** [comment]
You also need to work out the logic for registered users who have kept a secret phrase. I see this coin is based on the Bitcoin network.
I suggest, during authorization (shared/actions/user.js function sign), add a check if the secret phrase is deleted, and there is no private key for ghost, use the btc private key

**Comment by noxonsu** [comment]
https://github.com/swaponline/swap.core/pull/500 merged

**Comment by JoaoCampos89** [comment]
> You also need to work out the logic for registered users who have kept a secret phrase. I see this coin is based on the Bitcoin network.
> I suggest, during authorization (shared/actions/user.js function sign), add a check if the secret phrase is deleted, and there is no private key for ghost, use the btc private key

Prefix's are different how we will be using btc private key?

**Comment by noxonsu** [comment]
Please attach a video how it works

**Comment by JoaoCampos89** [comment]
Ghost wallet is created and it fetch balance from explorer, but something is missed to not show up on the wallet page as shown on the video.

[Hot Wallet with Atomic Swap Exchange - Google Chrome 2020-06-18 02-41-07.zip](https://github.com/swaponline/MultiCurrencyWallet/files/4796515/Hot.Wallet.with.Atomic.Swap.Exchange.-.Google.Chrome.2020-06-18.02-41-07.zip)

**Comment by shendel** [comment]
> This function is not duplicated?

Yes, we are update code, for use new Psbt, TransactionBuilder is deprecated and will be removed in next version of bitcoin-js

**Comment by shendel** [comment]
withdraw dont work (testnet tested)

**Comment by noxonsu** [comment]
Hi! thanks for your work, please describe why you start using bitcore-lib.js, bitcoinjs isn't working with your blockchain?

**Comment by JoaoCampos89** [comment]
Bitcoinjs is not working to build the transaction, tx's on ghost are with custom data that needs to be properly stripped of, bitcore is more simple and easy to use for it. Bitcoinjs lib's are used for the menmonic and wallet management, only export wif to use on Transaction lib of bitcore. Eventually I will add custom implementation to Bitcoinjs lib for transactions.

**Comment by JoaoCampos89** [comment]
image
When I click to start swap I am getting the follow error: 

image

Same it happens for btc-eth, so possibly is something related on ConfirmSwap Modal that is not working as intended

**Comment by Pasha8914** [comment]
> image
> When I click to start swap I am getting the follow error:
> 
> image
> 
> Same it happens for btc-eth, so possibly is something related on ConfirmSwap Modal that is not working as intended

fixed

**Comment by JoaoCampos89** [comment]
I went to create an order, and then try to fill it using Ghost-BTC, when I click it rings the browser and both browsers went blank:
I am getting follow errors on the browser:

image

The link is like this: http://localhost:9001/#/swaps/GHOST-BTC/QmS6qUWMk7PHZ78aJyLumUhFawHnNcMXGnXSHdCuKQHebk-1594166142620
and the browser it shows like this:

image

**Comment by noxonsu** [comment]
Errors with ipfs.io are just "warning" not critical.  They mean that browser can't connect to some nodes (for example 5 of 15 libp2p nodes are down)

**Comment by noxonsu** [comment]
- [ ] https://screenshots.wpmix.net/chrome_hZK64yoSNDmyARUQ4c5g2RmGt15GgHvh.png wallet dublicate
- [ ] blank screen after GHOST is sent from my wallet
- [ ] i sent 12 ghost, but see 12.0001 as pending https://screenshots.wpmix.net/chrome_dt5k2mkc62yWd3kkp8Tf4AjCKbosixGB.png

**Comment by JoaoCampos89** [comment]
Ghost Wallet related I think at the moment all works fine, now I need some guidance on the atomic swaps part, I created some swap components using as reference BtcToETH and EthToBtc only to not show up blank screen but it keeps showing blank when I try to do a swap, and the Swaps Home page is tied to ETH and BTC, idk if I need to add Ghost there, or if it loads out of the box. At the moment

**Comment by JoaoCampos89** [comment]
> * [ ]  https://screenshots.wpmix.net/chrome_hZK64yoSNDmyARUQ4c5g2RmGt15GgHvh.png wallet dublicate
> * [x]  blank screen after GHOST is sent from my wallet
> * [x]  blank screen on history page (possible https://testnet.ghostscan.io/ api is not available)

**Comment by JoaoCampos89** [comment]
The issue that I am having now is because SwapList and SwapProgress components are BTC or ETH, there is any example how I can add Ghost on this according to the swap flows? Guidance will be appreciated

**Comment by shendel** [comment]
Сделал по умолчанию, что ghost выключен. На этапе тестирования доступен на localhost и swaponline.github.io

**Comment by JoaoCampos89** [comment]
> * [x]  Update core submodule (after merge [swaponline/swap.core#501](https://github.com/swaponline/swap.core/pull/501))

**Comment by noxonsu** [comment]
Please resolve conflicts and attach video demo (exchange with 2 browsers)

**Comment by JoaoCampos89** [comment]
> * [ ]  Please resolve conflicts and attach video demo (exchange)

Which kind of video? The atomic swap between Ghost and ETH?

**Comment by noxonsu** [comment]
https://pr2891.swaponline.site/ deployed mainnet here

**Comment by reborn1002** [comment]
I am facing a bug:

Party A: Creates swap
Party B: Accept swap
Party A: Exits the page
Party B: There is no way to cancel the transaction

I tried to go to Wallet -> Ghost -> Swap History but there is no transaction showing there. So if Party A never logs back in I can not cancel either.

**Comment by reborn1002** [comment]
Another Bug I am facing:

If there is not enough ETH in the wallet for gas fee there is no notification or warning besides what is in the console log. There should be a popup or something to notify about this. For example transaction from USDT -> GHOST, you need to also have ETH in wallet for fee, but there is no notification besides error in console which most people don't know to check.

**Comment by akshaynexus** [comment]
Anything else needed from our side?

**Comment by noxonsu** [comment]
- [ ] resolve conflicts

**Comment by noxonsu** [comment]
https://pr2891.swaponline.site/ rebuilded

**Comment by noxonsu** [comment]
If i selling GHOST and my ETH balance is empty  empty notice and in console: "Error: Returned error: insufficient funds for gas * price + value)". I think it should be fixed later https://github.com/swaponline/MultiCurrencyWallet/issues/3141

**Comment by noxonsu** [comment]
tests
- [ ] creating an order
- [ ] starting a swap
- [ ] depositing GHOST
- [ ] depositing ETH
- [ ] withdrawing ETH
- [ ] withdrawing GHOST
- [ ] refund ETH
- [ ] refund GHOST

**Comment by noxonsu** [comment]
it works!!

**Comment by noxonsu** [comment]
> Another Bug I am facing:
> 
> If there is not enough ETH in the wallet for gas fee there is no notification or warning besides what is in the console log. There should be a popup or something to notify about this. For example transaction from USDT -> GHOST, you need to also have ETH in wallet for fee, but there is no notification besides error in console which most people don't know to check.

https://github.com/swaponline/MultiCurrencyWallet/issues/3141

**Pull request merged**
