### PR TITLE
Quickswap: form bugs

### PR DESCRIPTION
**Pull request by NotEternal**
## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/MultiCurrencyWallet/blob/master/docs/CONTRIBUTING.md) guide
- [ ] Good naming (as clear and simple as possible)
- [ ] Correct behavior if external API endpoints are down, return 404, 504 (or no answer), 401 errors (ddos simulation)
- [ ] I tested desktop/mobile resolution
- [x] I tested light/dark theme
- [ ] I tested different languages
- [ ] I checked the functionality once again (**AFFECT MONEY**)
- [x] I checked the work on the Testnet
- [x] I checked the work on the Mainnet
- [x] I checked the work in the plugin
- [ ] I checked the **PR** once again

## Tests

Please start auto tests as follows:

- add a label <ins>swap test</ins> to start swap tests
- add a label <ins>withdraw test</ins> to start withdraw tests

You can skip these tests if you completely sure that your changes aren't related to this functional

### Original issue

#

### Let users switch currency with different blockchains if they don't have assets on the current chain asset

image

### CODE REVIEW

**Comment by developer24-exe** [comment]
builded https://testnet4756.swaponline.site ;

**Comment by developer24-exe** [comment]
commit 0257d8a4b rebuilded https://testnet4756.swaponline.site https://mainnet4756.swaponline.site

**Comment by noxonsu** [comment]
- [ ] при клике на стркелки добавляется вопросик https://screenshots.wpmix.net/chrome_8PgTMeNdTmvhrmQFNjjzag2h0rictjIG.png

**Comment by developer24-exe** [comment]
commit cb0d7f14f rebuilded https://testnet4756.swaponline.site https://mainnet4756.swaponline.site

**Comment by developer24-exe** [comment]
commit 68d0507ab rebuilded https://testnet4756.swaponline.site https://mainnet4756.swaponline.site

**Comment by developer24-exe** [comment]
commit eae6dbea4 rebuilded https://testnet4756.swaponline.site https://mainnet4756.swaponline.site

**Comment by developer24-exe** [comment]
commit 0aaff8db0 rebuilded https://testnet4756.swaponline.site https://mainnet4756.swaponline.site

**Review by VitaliyShulik — APPROVED** [review]

**Pull request merged**
