### PR TITLE
Exchange: fee calculating in incognito, table row UI improvement. Cleanup

### PR DESCRIPTION
**Pull request by NotEternal**
## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/MultiCurrencyWallet/blob/master/docs/CONTRIBUTING.md) guide
- [x] Good naming (as clear and simple as possible)
- [x] I tested desktop/mobile resolution
- [x] I tested light/dark theme
- [ ] I tested different languages
- [ ] I checked the functionality once again (**AFFECT MONEY**)
- [x] I checked the **PR** once again

### Original issue
#4043
#3721

### Your offers row before 
before

### Your offers row after
after

### CODE REVIEW

**Comment by noxonsu** [comment]
итак форма показывает:

Miner fee: 0.0003 ETH + 0.00042925 BTC ≈ $24.41 (?)

https://ropsten.etherscan.io/tx/0xb92e2defaee89127d6b7b3fd58670f1e84cb6ccff899fe48945ada2aacc54ed8  0.000231664 Ether
https://live.blockcypher.com/btc-testnet/tx/ab4a464a05b6526e512dab7b814957d23bb0b579b4a18dca1984f01b88fab495/ ab4a464a05b6526e512dab7b814957d23bb0b579b4a18dca1984f01b88fab495  fees 0.00013191 BTC

эфир более менее правильно, а вот биток завышено показывает раза в два

**Comment by noxonsu** [comment]
- [ ] если отдаем биткин и стоит отправка с extrenal wallet то убрать btc из расчетов.

**Review by iower — APPROVED** [review]
Seems OK

**Comment by shendel** [comment]
https://github.com/swaponline/MultiCurrencyWallet/blob/e8f46daa1814cef05c715f0bc871b394617b5b38/src/front/shared/helpers/btc.ts#L131

send = swap_deposit
добавить еще swap_withdraw, если этот метод, то используем один unspent

**Pull request merged**
