### PR TITLE
Upgrade react redux

### PR DESCRIPTION
**Pull request by alyavasilyeva**
## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] Good naming, keep simple
- [ ] Tested desktop/mobile
- [ ] Tested bright/dark
- [ ] Tested en/ru
- [x] Affects money; I checked the functionality once again
- [x] I checked the PR once again

### Original issue

#

### Video / screenshot proof

При изменении версии react-redux ломается ConnectedRouter из react-router-redux. Судя по их репозиторию, модуль больше не поддерживается, рекомендуют использовать connected-react-router (https://github.com/supasate/connected-react-router). После его подключения возникла новая ошибка `Uncaught Could not find router reducer in state tree, it must be mounted under "router"` варианты решения были здесь - https://github.com/supasate/connected-react-router/issues/312. Даунгрейд history не помог.

### CODE REVIEW

**Review by iower — CHANGES_REQUESTED** [review]
Runtime error (broken modals)
image

Possibly, because of `combineReducers` from non-standard [redaction](https://www.npmjs.com/package/redaction) lib:
https://github.com/swaponline/MultiCurrencyWallet/pull/3690/files#diff-401e0d4494e58ae90a2fb3da87f0d032ecc843571893080f68a598a3988bbfc6R20

---
`combineReducers` from `redaction`: [source](https://github.com/pavelivanov/redaction/blob/master/src/combineReducers.js)
`combineReducers` from `redux`: [source](https://github.com/reduxjs/redux/blob/master/src/combineReducers.ts)
are quite different

**Comment by Pasha8914** [comment]
export const createReducer = () =>
  combineReducers({
    router: connectRouter(history),
    combineReducers({...reducers})
  })



export const configureStore = (initialState, history) => {
  const storeEnhancers = []

  const composeEnhancers = process.env.NODE_ENV === 'development' ? composeWithDevTools({}) : compose
  const middlewareEnhancer = applyMiddleware(routerMiddleware(history))

  storeEnhancers.unshift(composeEnhancers(middlewareEnhancer))

  const reducer = createReducer()
  const store = createStore(reducer, initialState, compose(...storeEnhancers))

  return { store }
}

const { store } = configureStore(initialState, history)

<Provider store={store}>
  <ConnectedRouter history={history}>
    {allRoute}
  </ConnectedRouter>
</Provider>

**Comment by shendel** [comment]
`redaction` - это обертка над `redux`

**Comment by shendel** [comment]
> Runtime error (broken modals)
> image
> 
> Possibly, because of `combineReducers` from non-standard [redaction](https://www.npmjs.com/package/redaction) lib:
> https://github.com/swaponline/MultiCurrencyWallet/pull/3690/files#diff-401e0d4494e58ae90a2fb3da87f0d032ecc843571893080f68a598a3988bbfc6R20
> 
> `combineReducers` from `redaction`: [source](https://github.com/pavelivanov/redaction/blob/master/src/combineReducers.js)
> and
> `combineReducers` from `redux`: [source](https://github.com/reduxjs/redux/blob/master/src/combineReducers.ts)
> are quite different
> 
> ### Possible solution
> Replace `redaction` -> `redux` ?

В пределах страницы все работает уже
При переходе между разделами - фейл, включая не работающих модальных окон
Причина в запутанном 'history' - При снисхождении от Root до ModalConductor, history становиться window.history, и это только одна из проблем (с потерей history)

**Comment by shendel** [comment]
Вынес `redaction` в `common` (из package не удалял еще) - это по сути обертка над `redux`, но весь проект завязан на ней, так будет проще отлаживать и поддерживать

**Review by noxonsu — APPROVED** [review]
отправку эфира с метамаск и свап проверил, работает

**Review by iower — APPROVED** [review]
Tested, seems OK

**Pull request merged**
