### PR TITLE
Add Branding Feature - Needs Feedback

### PR DESCRIPTION
**Pull request by JoaoCampos89**
## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] Styleguide check `npm run validate`
- [x] Good naming, keep simple
- [x] Tested desktop/mobile
- [x] Tested bright/dark
- [x] Tested en/ru
- [x] Affects money; I checked the functionality once again
- [x] I checked the PR once again

### Original issue
 #3345 
#

### Video / screenshot proof
The original layout:
vars1
Colours branding was moved to index html using css vars
vars2
Changing the primary colour now is possible to brand all app at once
vars4
Looking like this:
vars3

Some buttons are not using the primary color, for instance the "Add Currency"? What will be a solution, branding all buttons to look and feel the same and use the same colours through all the app?

The current vars solutions works good on Chrome, still need to be tested how it looks on Firefox and Brave.

The current solution allows the usage inside wordpress plugin easily as it only need to change the vars on index.html file

### CODE REVIEW

**Review by shendel — APPROVED** [review]

**Review by iower — APPROVED** [review]

**Comment by noxonsu** [comment]
@JoaoCampos89 merge?

**Comment by JoaoCampos89** [comment]
@noxonsu what about the questions I made, do you have any answers for them?

**Comment by iower** [comment]
> What will be a solution, branding all buttons to look and feel the same and use the same colours through all the app?

The one color scheme for all buttons is useful for UX. I see no reason for exceptions.

Look at the example from metamask:
image
Buttons have one color, but may vary fullness (also may have icons).

The <kbd>Add currency</kbd> button **may have brand color** and be non-filled - like second button.

Сonsistency matters!

**Comment by noxonsu** [comment]
@JoaoCampos89 let's use primary color on "add currency" button. can you remove WIP?

**Comment by JoaoCampos89** [comment]
@noxonsu I removed WIP. I recommend after do a review in all branding to follow always the same pattern for buttons, links and so on, to all feel like the same.

**Pull request merged**
