### PR TITLE
Fix - Breaked wp build

### PR DESCRIPTION
**Pull request by shendel**
## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/swaponline/MultiCurrencyWallet/blob/master/docs/CONTRIBUTING.md) guide
- [ ] Good naming (as clear and simple as possible)
- [ ] Correct behavior if external API endpoints are down, return 404, 504 (or no answer), 401 errors (ddos simulation)
- [ ] I tested desktop/mobile resolution
- [ ] I tested light/dark theme
- [ ] I tested different languages
- [ ] I checked the functionality once again (**AFFECT MONEY**)
- [ ] I checked the work on the Testnet
- [ ] I checked the work on the Mainnet
- [ ] I checked the work in the plugin
- [ ] I checked the **PR** once again

## Tests

Please start auto tests as follows:

- add a label <ins>swap test</ins> to start swap tests
- add a label <ins>withdraw test</ins> to start withdraw tests

You can skip these tests if you completely sure that your changes aren't related to this functional

### Original issue
https://github.com/swaponline/MultiCurrencyWallet/issues/4715
#

### CODE REVIEW

**Comment by developer24-exe** [comment]
builded https://testnet4716.swaponline.site ;

**Comment by developer24-exe** [comment]
commit 617a7d6ec rebuilded https://testnet4716.swaponline.site https://mainnet4716.swaponline.site

**Comment by developer24-exe** [comment]
builded https://testnet4716.swaponline.site ;

**Comment by developer24-exe** [comment]
commit 71cf38061 rebuilded https://testnet4716.swaponline.site https://mainnet4716.swaponline.site

**Review by noxonsu — APPROVED** [review]

**Pull request merged**
