### PR TITLE
Connected account modal: interface. Quickswap: better currency filter. Cleanup

### PR DESCRIPTION
**Pull request by NotEternal**
## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/MultiCurrencyWallet/blob/master/docs/CONTRIBUTING.md) guide
- [x] Good naming (as clear and simple as possible)
- [ ] Correct behavior if external API endpoints are down, return 404, 504 (or no answer), 401 errors (ddos simulation)
- [x] I tested desktop/mobile resolution
- [x] I tested light/dark theme
- [ ] I tested different languages
- [ ] I checked the functionality once again (**AFFECT MONEY**)
- [ ] I checked the work on the Testnet
- [x] I checked the work on the Mainnet
- [ ] I checked the work in the plugin
- [x] I checked the **PR** once again

## Tests

Please start auto tests as follows:

- add a label <ins>swap test</ins> to start swap tests
- add a label <ins>withdraw test</ins> to start withdraw tests

You can skip these tests if you completely sure that your changes aren't related to this functional

### Original issue
#3511
#4779
#4785

### Video / screenshot proof
image

#### Disconnected state
image

image

### CODE REVIEW

**Comment by developer24-exe** [comment]
builded https://testnet4784.swaponline.site ;

**Comment by developer24-exe** [comment]
commit 6e0744179 rebuilded https://testnet4784.swaponline.site https://mainnet4784.swaponline.site

**Comment by developer24-exe** [comment]
commit 7221a101c rebuilded https://testnet4784.swaponline.site https://mainnet4784.swaponline.site

**Comment by developer24-exe** [comment]
commit 0c6bbaf16 rebuilded https://testnet4784.swaponline.site https://mainnet4784.swaponline.site

**Comment by developer24-exe** [comment]
commit 3fe324001 rebuilded https://testnet4784.swaponline.site https://mainnet4784.swaponline.site

**Review by VitaliyShulik — APPROVED** [review]

**Comment by VitaliyShulik** [comment]
при подключении arbitrum через метамаск  на странице quickswap- выходит эта ошибка

Screen Shot 2021-09-15 at 20 28 10

**Comment by NotEternal** [comment]
> при подключении arbitrum через метамаск на странице quickswap- выходит эта ошибка
> 
> Screen Shot 2021-09-15 at 20 28 10

поправил

**Comment by developer24-exe** [comment]
commit c7e2bea1a rebuilded https://testnet4784.swaponline.site https://mainnet4784.swaponline.site

**Comment by NotEternal** [comment]
тесты не проходят, так как арбитрум тестнет рпс не отвечает. С мейннетом все нормально

**Pull request merged**
